# Generated by Django 4.1.4 on 2022-12-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10)),
                ('code', models.IntegerField(max_length=10)),
                ('tag', models.CharField(max_length=20)),
                ('time_zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('text', models.TextField(max_length=255)),
                ('code_client', models.IntegerField(default=0, max_length=10)),
                ('time_zone_client', models.CharField(default=0, max_length=50)),
                ('time_ended', models.DateTimeField(default='2012-12-12 12:12:12')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapp.client')),
                ('id_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapp.mailing')),
            ],
        ),
    ]
